Algoritmo "TipoDados"
//
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/01/2024
Var
// Seção de Declarações das variáveis


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Nome: Saulo.")
Escreval("Idade:", 35, ".")
Escreval("Altura:", 1.70, ".")
Escreval("Criança?", falso, ".")

Fimalgoritmo
